/// app metadata
library;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{description: This package can work with a variety of ONVIF compatible devices allowing for IP Cameras and NVRs (network video recorders) to be integrated into Dart and Flutter applications., homepage: https://github.com/faithoflifedev/packacges/easy_onvif, documentation: null, repository: https://github.com/faithoflifedev/easy_onvif_workspace, issueTracker: null, name: easy_onvif, publish_to: null, version: 3.1.1+4}');
