/// DO NOT EDIT THIS FILE
/// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{"name":"easy_onvif","version":"2.1.0-dev.5","homepage":"https://github.com/faithoflifedev/easy_onvif","environment":{"sdk":">=2.19.2 <4.0.0"},"description":"A pure Dart library designed primarily for command line automation of Onvif compatible devices, but can be used anywhere Dart is used.","dependencies":{"args":"^2.3.1","crypto":"^3.0.2","dio":"^5.0.2","intl":"^0.18.0","json_annotation":"^4.8.0","loggy":"^2.0.3","sprintf":"^7.0.0","universal_io":"^2.2.0","uuid":"^3.0.7","xml":"^6.2.2","xml2json":"^5.3.6","yaml":"^3.1.1"},"dev_dependencies":{"build_runner":"^2.3.3","grinder":"^0.9.2","http":"^0.13.5","json_serializable":"^6.6.1","lints":"^2.0.1","mustache_template":"^2.0.0","process_run":"^0.12.3+2","pub_semver":"^2.1.3","publish_tools":"^0.1.0+10","pubspec":"^2.3.0","test":"^1.22.1"},"executables":{"onvif":""},"repository":"https://github.com/faithoflifedev/easy_onvif"}');
