/// app metadata
library;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{"name":"easy_onvif","version":"3.1.0","homepage":"https://github.com/faithoflifedev/easy_onvif","environment":{"sdk":">=3.3.0 <4.0.0"},"description":"A pure Dart library designed primarily for command line automation of Onvif compatible devices, but can be used anywhere Dart is used.","dependencies":{"convert":"^3.1.1","crypto":"^3.0.5","dio":"^5.7.0","ffi":"^2.1.3","html_unescape":"^2.0.0","http":"^1.2.2","http_parser":"^4.1.0","intl":"^0.19.0","json_annotation":"^4.9.0","loggy":"^2.0.3","path":"^1.9.0","uuid":"^4.5.1","xml":"^6.5.0","xml2json":"^6.2.4","yaml":"^3.1.2"},"dev_dependencies":{"build_runner":"^2.4.12","json_serializable":"^6.8.0","lints":"^5.0.0","publish_tools":"^1.0.0+5","test":"^1.25.8"},"executables":{"onvif":""},"repository":"https://github.com/faithoflifedev/easy_onvif"}');
