/// DO NOT EDIT THIS FILE EXCEPT TO ENTER INITIAL VERSION AND OTHER META INFO 
/// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY MetaUpdate 

Map<String, String> meta = <String, String>{
  "name": "easy_onvif",
  "description":
      // ignore: lines_longer_than_80_chars
      "A pure Dart library designed primarily for command line automation of Onvif compatible devices, but can be used anywhere Dart is used.",  
  "version":"2.0.13+1",
};
  