/// DO NOT EDIT THIS FILE EXCEPT TO ENTER INITIAL VERSION AND OTHER META INFO
/// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY MetaUpdate

Map<String, String> meta = <String, String>{
  "name": "yt",
  "description":
      // ignore: lines_longer_than_80_chars
      "Native Dart interface to multiple YouTube REST APIs including the Data API and Live Streaming API.",
  "version": "2.0.5",
};
