/// app metadata
library;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{"name":"onvif_cli","version":"3.1.0","homepage":"https://github.com/faithoflifedev/easy_onvif_workspace/packages/easy_onvif_cli","publish_to":"none","environment":{"sdk":">=3.3.0 <4.0.0"},"description":"A pure Dart library designed primarily for command line automation of Onvif compatible devices, but can be used anywhere Dart is used.","dependencies":{"archive":"^3.6.1","args":"^2.4.2","ansicolor":"^2.0.3","ansi_escapes":"^1.1.0","cli_spin":"^1.0.1","easy_onvif":{"path":"../easy_onvif"},"dio":"^5.7.0","loggy":"^2.0.3","path":"^1.9.0","shelf":"^1.4.2","shelf_router":"^1.1.4","uuid":"^4.5.1","yaml":"^3.1.2"},"dev_dependencies":{"publish_tools":"^1.0.0+5"},"executables":{"onvif":""},"repository":"https://github.com/faithoflifedev/easy_onvif_workspace","funding":["https://www.buymeacoffee.com/faithoflif2"]}');
